server:
  port: 8000
  secret-key: "secret key for stored sessions"
  base-url: "base api url, trailing slash"
  sonolus-server-url: "sonolus server url, trailing slash"
  sonolus-server-chart-prefix: "sonolus server chart prefix, eg. UnCh-"
  force-https: False # on the / link redirects
  # Should match sonolus backend auth
  # Should not be given out
  auth: "required auth"
  auth-header: "random auth header (CANNOT BE 'authorization'!)"
  token-secret-key: "256bit key (or whatever)"
  debug: false
s3:
  base-url: "..." # public access url where public can access your items
  endpoint: "..." # endpoint for requests
  bucket-name: "..."
  access-key-id: "..."
  secret-access-key: "..."
  location: "auto" # note: auto is for R2 cloudflare only.
psql:
  host: "..."
  user: "..."
  database: "..."
  port: 5432
  password: "..."
  pool-min-size: 10
  pool-max-size: 20
discord:
  # webhook settings
  avatar-url: ""
  username: ""
  # new published songs, first time only
  published-webhook: ""
  staff-pick-webhook: ""
  # for moderation
  new-uploads-webhook: ""
  all-visibility-changes-webhook: ""
  comments-webhook: ""
oauth:
  discord-client-id: ""
  discord-client-secret: ""
  required-discord-server: 1234567890